### ISSUE TITLE
Update design using Vanilla

### ISSUE THREAD

**Issue by anthonydillon** [canonical-web-and-design/dqlite.io#4]

**Comment by anthonydillon** [comment]
@anasereijo once #3 lands I will build staging. Then could you review that page and give design tips to make it look nice. Thanks.

**Comment by anthonydillon** [comment]
@anasereijo this is now done and ready for review: Please review https://staging.dqlite.io/ and let me know what should change.

**Comment by anasereijo** [comment]
- [ ] Navigation isn't properly aligned with the rest of the page

![Dqlite - High-Availability SQLite](https://user-images.githubusercontent.com/36884067/63844785-b61f1d00-c980-11e9-9712-6305d2e42e34.png)

- [ ] typo

![Dqlite - High-Availability SQLite (1)](https://user-images.githubusercontent.com/36884067/63844944-026a5d00-c981-11e9-8c15-5600543f62ac.png)


- [ ] mobile: please hide the top line from the following section:

<img width="400" alt="Screenshot 2019-08-28 at 10 50 00" src="https://user-images.githubusercontent.com/36884067/63845520-faf78380-c981-11e9-8a78-c37b4b3a82b6.png">
