### ISSUE TITLE
Add link to documentation

### ISSUE THREAD

**Issue by anthonydillon** [canonical-web-and-design/dqlite.io#5]

**Comment by anthonydillon** [comment]
@nottrobin do you think its best to link directly to the MD files in the GH project until discourse is ready or clone the MD's in to the site and render the docs statically.

**Comment by nottrobin** [comment]
@anthonydillon where are the docs now?

I think we should include and render the docs in the site.

**Comment by anthonydillon** [comment]
@nottrobin the docs are currently [markdown files in the project](https://github.com/canonical/dqlite/tree/master/doc). Free is going to add a index so we have a place for /docs to land on.

**Comment by nottrobin** [comment]
@anthonydillon are they happy to move the docs into the dqlite.io codebase?

**Comment by anthonydillon** [comment]
@nottrobin happy to do so, but would need to set up a docs template and theme which would take a bit of time which will be undone once discourse is available.

**Comment by nottrobin** [comment]
@anthonydillon is it undone? surely the template would be pretty similar whether the content comes from Discourse or Markdown files.

**Comment by anthonydillon** [comment]
@nottrobin ok will get it done today
