### ISSUE TITLE
Circle CI config is used in place of GH workflow

### ISSUE THREAD

**Issue by bartaz** [canonical-web-and-design/dqlite.io#53]
Project has a PR workflow set up in `.github/workflows/pr.yml`, 

https://github.com/canonical-web-and-design/dqlite.io/blob/8cb4237080f28b7d8d7b7a7c1a4074fa4fc8b7a7/.github/workflows/pr.yml#L1-L9

but this file uses Circle CI config format instead of GitHub actions. This causes workflow to fail on every push to the repo:
https://github.com/canonical-web-and-design/dqlite.io/actions

**Comment by anthonydillon** [comment]
Thanks for the heads up.

**Comment by carkod** [comment]
This has been fixed with PR #55
